apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pynotes-data
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/containers/back-hekima/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pynotes-logs
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/containers/back-hekima/logs
