apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ko-store
  labels:
    type: local
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/data/korean-subs/store
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-ko-store-claim
spec:
  volumeName: pv-ko-store
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi