apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ko-store
  labels:
    type: local
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/data/korean-subs/store
