apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
  labels:
    app: notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
        - name: notes
          image: jleobernard/notes:2.1.5
#          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: notes-storage
              mountPath: /kosubs
            - name: notes-data
              mountPath: /data
            - name: notes-logs
              mountPath: /logs
            - name: notes-secrets
              mountPath: /secrets
          env:
            - name: SPRING_PROFILE
              value: validation -Dsubs.store.path=/kosubs -Ddata.dir=/data/upload
            - name: JAVA_OPTS
              value: -Xms128m -Xmx2048m
            - name: NOTES_DB_HOST
              valueFrom:
                configMapKeyRef:
                 name: postgres-configmap
                 key: database_url
            - name: NOTES_DB_PORT
              value: "5432"
            - name: NOTES_DB_NAME
              value: notes
            - name: NOTES_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: notes-db-user
            - name: NOTES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: notes-db-password
            - name: NOTES_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: notes-jwt-key
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/fcm.json
            - name: CLIPPER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: clipper-configmap
                  key: clipper_url
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: notes-storage
          persistentVolumeClaim:
            claimName: pv-ko-store-claim
        - name: notes-data
          persistentVolumeClaim:
            claimName: notes-pv-claim-data
        - name: notes-logs
          persistentVolumeClaim:
            claimName: notes-pv-claim-logs
        - name: notes-secrets
          secret:
            secretName: commons-secret
            optional: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pv-claim-data
spec:
  volumeName: pv-notes-data
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pv-claim-logs
spec:
  volumeName: pv-notes-logs
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notes-service
spec:
  selector:
    app: notes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-static
  labels:
    app: notes-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-static
  template:
    metadata:
      labels:
        app: notes-static
    spec:
      containers:
        - name: notes
          image: jleobernard/notes-front:1.1.0
#          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: kosubs-storage
              mountPath: /kosubs
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: kosubs-storage
          persistentVolumeClaim:
            claimName: pv-ko-store-claim
---
apiVersion: v1
kind: Service
metadata:
  name: notes-static
spec:
  selector:
    app: notes-static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

