apiVersion: apps/v1
kind: Deployment
metadata:
  name: clipper-deployment
  labels:
    app: clipper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clipper
  template:
    metadata:
      labels:
        app: clipper
    spec:
      containers:
        - name: clipper
          image: jleobernard/clipper:1.0.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: clipper-storage
              mountPath: /opt/data/korean-subs/store
          env:
            - name: CLIP_CONF_FILE_PATH
              value: /go/go-clipper/env.json
      volumes:
        - name: clipper-storage
          persistentVolumeClaim:
            claimName: pv-ko-store-claim
---
apiVersion: v1
kind: Service
metadata:
  name: clipper-service
spec:
  selector:
    app: clipper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

